{
  "title": "Use of Sleep() function (twice)",
  "link": "https://reverseengineering.stackexchange.com/questions/7997/use-of-sleep-function-twice",
  "content": "during an analysis, I have found the following :\n\n```\n  ...\n  call program.00401535\n  ...\n  (a few lines later)\n  ...\n  ...\n  call program.00401535\n  ...\n  ...\n\n```\nSo, it call the same function. When I step over that first call, nothing happens. But later, when I step over the second call, suddenly I get the message \"000004C0 terminated, exit code 0\" and ollydbg is running, running...and running.\nSo, I have decided to look into that function and I see the following:\n\n```\n                    PUSH EBP\n                    MOV EBP, ESP\n 00401538           PUSH 1000\n     |              CALL DWORD PTR DS:[40241C]    ; which is kernel32.Sleep\n     -------------- JMP  SHORT program.00401538\n                    LEAVE \n                    RETN\n\n```\nSo, it is simple what it is doing here. Since we have unconditional jump, it always lets the program sleep for a while. In other words, that function should never return.\n\nBut my question would be:\nWhy it was possible for me to step over the first call, and not over the second ?\nI googled for Sleep() as anti-debugging trick but I did not find anything about that. \nCan somebody tell me what can I do in such a case?\n\nbest regards,\n\n",
  "votes": "0",
  "answers": 2,
  "views": "2k",
  "tags": [
    "assembly"
  ],
  "user": "user3097712",
  "time": "Dec 16, 2015 at 17:43",
  "comments": [],
  "answers_data": [
    {
      "content": "Are you sure the contents of DS:[40241C] haven't been changed between the first and the second call? Maybe it's not the sleep function called at all, at the first time.\n\nSomething like\n\n```\n....\nfptr=generateException;\nExceptionReturnOrEndleesLoop();\nif (shenanigans) {\n    fptr=sleep;\n    ExceptionReturnOrEndlessLoop();\n}\n\nExceptionReturnOrEndlessLoop() {\n    for (;;) {\n        try {\n            (*fptr);\n        } catch  (someexception Ex) {\n            return;\n        }\n    }\n}\n\n```\nOr even, have the function pointer refer sleep() all the time, but create a second thread that waits for exactly 500 ms, then interrupts the main thread (and the sleep, thus causing an exception). If you're singlestepping, the interrupt will occur before the sleep() gets executed, and the exception handler won't ever get executed.\n\n",
      "votes": "1",
      "user": "Guntram Blohm",
      "time": "Jan 11, 2015 at 17:29",
      "is_accepted": false,
      "comments": [
        {
          "user": "PhoeniX",
          "text": "To start digging, you can break on TerminateProcess, TerminateThread and analyse the stack. This will help to find what thread/code is responsible to nock you out.",
          "time": null
        }
      ]
    },
    {
      "content": "This is a possible scenario in a multithreaded application. Here the anti-debugging check is run in a dedicated thread. When the main thread calls Sleep, it means that it is giving up cpu-time so that the other thread have higher chances to execute.\n\nTo debug such an application in Ollydbg, look in the threads Window. If you find another thread running, you need to analyze it too.\n\n",
      "votes": "0",
      "user": "0xec",
      "time": "Jan 11, 2015 at 17:25",
      "is_accepted": false,
      "comments": [
        {
          "user": "PhoeniX",
          "text": "Just to add to the above, in Options->Debug->Events menu, you can ask to break on every new thread to ensure that you will not miss anything. You will likely to do it in several inebriations to find the \"bad\" thread.",
          "time": null
        }
      ]
    }
  ]
}