{
    "title": "IDAPython Strings constantly returns NoneType with str()",
    "link": "https://reverseengineering.stackexchange.com/questions/11044/idapython-strings-constantly-returns-nonetype-with-str",
    "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>I'm trying to automate  disassembly of a firmware image using IDA Pro 6.5 and IDA Python. One of the process I want to implement is to locate strings and create a data segment around them.</p>\n<p>Using the GUI, I have little issue doing so. However when using the <a href=\"https://www.hex-rays.com/products/ida/support/idapython_docs/idautils.Strings.StringItem-class.html\" rel=\"nofollow noreferrer\"><code>idautils.Strings()</code></a> API call, I can retrieve a list of <code>StringItem</code> objects, but I fail to access the actual string data with <code>str()</code> or <code>unicode()</code>. Below is the failing function, which is taken from <a href=\"https://code.google.com/p/idapython/source/browse/trunk/examples/ex_strings.py?r=344\" rel=\"nofollow noreferrer\">IDA Python Google Code archive</a>:</p>\n<pre><code>def find_strings():\n    s = idautils.Strings(False)\n    s.setup(strtypes=Strings.STR_UNICODE | Strings.STR_C)\n    for i, v in enumerate(s):\n        if v is None:\n            print(\"Failed to retrieve string index %d\" % i)\n        else:\n            print(\"%x: len=%d type=%d index=%d-&gt; '%s'\" % (v.ea, v.length, v.type, i, str(v)))\n</code></pre>\n<p>When ran into IDA, the following error is reported:</p>\n<pre><code>Traceback (most recent call last):\n  File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n  File \"&lt;string&gt;\", line 8, in find_strings\nTypeError: 'StringItem' object is not callable\n</code></pre>\n<p>When replacing the <code>str(v)</code> argument with the constant <code>aaa</code> in the <code>print</code> function, I get a list of <code>StringItem</code> objects without any problem:</p>\n<pre><code>Python&gt;find_strings()\n208e: len=8 type=3 index=0-&gt; 'aaa'\n21b0: len=55 type=0 index=1-&gt; 'aaa'\n229d: len=6 type=0 index=2-&gt; 'aaa'\n22c5: len=5 type=0 index=3-&gt; 'aaa'\n22d3: len=33 type=0 index=4-&gt; 'aaa'\n...\n</code></pre>\n<p>If I attempt to use the <code>unicode()</code> function instead, I get the following error:</p>\n<pre><code>Python&gt;find_strings()\n208e: len=8 type=3 index=0-&gt; '\nTraceback (most recent call last):\n  File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n  File \"&lt;string&gt;\", line 8, in find_strings\nTypeError: coercing to Unicode: need string or buffer, NoneType found\n</code></pre>\n<p>From my understanding, it seems that the <code>StringItem</code> contains no strings for an unknown reason (or an issue with the plugin, specific version of Python maybe?), however they are displayed in the GUI.</p>\n<p>I'm seeking advice on either what I'm doing wrong, or an alternative way to extract the strings using the IDApython plugin. Thanks</p>\n<h2>Updates</h2>\n<p>The code above appears valid after adding the missing parenthesis as mentioned in the comments. However this was only a typo in the post and not the source of the issue. The <code>find_strings</code> worked fine in other typical binaries. Further proof is that by using the <code>idc.GetString(self.ea, self.length, self.type)</code> also returned <code>NoneType</code>.</p>\n<p>Diff mentioned that the <code>get_ascii_contents2</code> is failing and thus returning <code>null</code>, which is very likely the cause. What is unclear is why the function is failing, while the GUI succeeds in locating most of the strings.</p>\n<p>The first string at 0x208E is a trash Unicode string. The string at 0x21B0 is an actual ASCII string composed of 37 chars. I cannot post the complete string due to disclosure/legal issues. Notice that when displayed in the hex editor, the byte order of the ASCII view is inverted for an unknown reason. The bitness of the overall firmware is 16bit.</p>\n<p><code>434F 5059 5249 4748 5420 A920 ... 4544 2000 0000 : OCYPIRHG T Â¬ ... DE.</code></p>\n<p>Finally, note that the function <code>MakeStr</code> works without any issue. I have the following code, when used at 0x21B0, will successfully create a string within a data segment:</p>\n<pre><code>def create_string(self, _startea, _endea, _segname=\".const\", _unicode=False):\n        \n        if (SegStart(_startea) == idc.BADADDR):\n            self.create_data_segment(_startea, _endea, \".const\")\n        else:\n            segtype = GetSegmentAttr(_startea, SEGATTR_TYPE)\n            if (segtype != IDAEngine.SEG_TYPE_DATA):\n                DelSeg(_startea, 0)\n                self.create_data_segment(_startea, _endea, _segname)\n        \n        result = MakeStr(_startea, _endea)\n        if (result == IDAEngine.FAIL):\n            print \"[-] Failed to create a string at 0x{:x} to 0x{:x}.\".format(_startea, _endea)\n</code></pre>\n<p>At this point, I believe the structure of the firmware is to blame (combination of bitness, lack of symbols and an obsolete but supported microprocessor), however I couldn't pinpoint the exact issue. For now, since I can use <code>find_strings()</code> to retrieve the offsets and then use <code>MakeStr</code> on strings with a certain length and the manually vetting the \"real\" strings.</p>\n<h2>Final Remarks</h2>\n<p>For posterity, I never really solved the issue, however I can confirm the underlying binary file was responsible for raising an exception in <code>get_ascii_contents2</code>. I've reloaded the same file, however as a raw binary file in one large segment and the function worked flawlessly.</p>\n</div>",
    "votes": "4",
    "answers": 1,
    "views": "2k",
    "tags": [
        "ida",
        "idapython",
        "ida-plugin"
    ],
    "user": "InfectedPacket",
    "time": "Jun 17, 2020 at 9:54",
    "comments": [
        {
            "user": "diff",
            "text": "<span class=\"comment-copy\">You're missing a <code>)</code> in the last line of code, the fixed version would be; <code>print(\"%x: len=%d type=%d index=%d-&gt; '%s'\" % (v.ea, v.length, v.type, i, str(v)))</code>  With that fix the script works fine on my machine. Is this not the issue?</span>",
            "time": null
        },
        {
            "user": "InfectedPacket",
            "text": "<span class=\"comment-copy\">Unfortunately, it appears the missing parenthesis was due to a bad copy-paste. My code actually contains the extra parenthesis. Additionally, I've been trying to use <code>idc.GetString(self.ea, self.length, self.type)</code> with the same result. I suspect the format of the binary file is somehow to blame. The firmware I'm looking at is not a well known architecture (not Intel, ARM or MIPS...)</span>",
            "time": null
        },
        {
            "user": "tmr232",
            "text": "<span class=\"comment-copy\">This does not reproduce for me. Are you using latest IDAPython?</span>",
            "time": null
        },
        {
            "user": "diff",
            "text": "<span class=\"comment-copy\">Agreed, after fixing the typo the code worked fine as well.</span>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>This took some digging, however it appears you're hitting an interesting edge case that the original author of the scripts didn't consider.</p>\n<p><code>str(StringItem)</code> calls the following code inside <a href=\"https://github.com/idapython/src/blob/0369202c370b9701cd2b2a46e63c2919bf0a7ba0/python/idautils.py#L509\" rel=\"nofollow\">idautils.py</a>;</p>\n<pre><code>    def __str__(self):\n        return self._toseq(False)\n</code></pre>\n<p>Which leads to <code>_toseq</code> in <a href=\"https://github.com/idapython/src/blob/0369202c370b9701cd2b2a46e63c2919bf0a7ba0/python/idautils.py#L496\" rel=\"nofollow\">idautils.py</a>;</p>\n<pre><code>    def _toseq(self, as_unicode):\n        if self.is_2_bytes_encoding():\n            conv = idaapi.ACFOPT_UTF16\n            pyenc = \"utf-16\"\n        elif self.is_4_bytes_encoding():\n            conv = idaapi.ACFOPT_UTF8\n            pyenc = \"utf-8\"\n        else:\n            conv = idaapi.ACFOPT_ASCII\n            pyenc = 'ascii'\n        strbytes = idaapi.get_ascii_contents2(self.ea, self.length, self.type, conv)\n        return unicode(strbytes, pyenc, 'replace') if as_unicode else strbytes\n</code></pre>\n<p>If we dig into the <code>get_ascii_contents2</code> inside <a href=\"https://github.com/idapython/src/blob/master/pywraps/py_bytes.hpp#L186\" rel=\"nofollow\">py_bytes.hpp</a> method we see that this method could actually return a <code>NoneType</code> if <code>get_ascii_contents2</code> fails;</p>\n<pre><code>if ( !get_ascii_contents2(ea, len, type, buf, len+1, &amp;used_size, flags) )\n{\n  qfree(buf);\n  Py_RETURN_NONE;\n}\n</code></pre>\n<p>Essentially, the code is fine, however you should add a check or exception handling if a <code>str(StringItem)</code> returns the with a <code>TypeNone</code> since it is possible for this type of value to be returned.</p>\n<p>You could help debug further by providing what the hex data is at <code>ea</code> of <code>0x208e</code> with the length of <code>8</code> as shown in your output;</p>\n<pre><code>208e: len=8 type=3 index=0-&gt;\n</code></pre>\n</div>",
            "votes": "2",
            "user": "diff",
            "time": "Oct 14, 2015 at 18:31",
            "is_accepted": true,
            "comments": [
                {
                    "user": "InfectedPacket",
                    "text": "<span class=\"comment-copy\">Your description is likely what is happening, i.e. <code>get_ascii_contents2</code> is failing. The <code>find_strings</code> function worked in other files, I therefore suspect the cause is the way words are ordered within the firmware, despite finding the strings correctly using the GUI. I'll post some examples of hex words in my post.</span>",
                    "time": null
                }
            ]
        }
    ]
}