{
    "title": "When is EXCEPTION_REGISTRATION_RECORD created on the stack?",
    "link": "https://reverseengineering.stackexchange.com/questions/31559/when-is-exception-registration-record-created-on-the-stack",
    "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>I want to understand when <code>EXCEPTION_REGISTRATION_RECORD</code>s get created on the stack.</p>\n<ul>\n<li>Are they created when the program starts?</li>\n<li>Are they created when we enter the function?</li>\n<li>Or are they created only when the exception occurs?</li>\n</ul>\n<p>Is it true that there is one <code>EXCEPTION_REGISTRATION_RECORD</code> per <code>try</code>/<code>catch</code>?</p>\n</div>",
    "votes": "3",
    "answers": 1,
    "views": "99",
    "tags": [
        "seh"
    ],
    "user": "Bob5421",
    "time": "Feb 17, 2023 at 9:40",
    "comments": [
        {
            "user": "0xC0000022L",
            "text": "<span class=\"comment-copy\">Could you please clarify one thing. You tagged it as <a href=\"https://reverseengineering.stackexchange.com/questions/tagged/seh\">seh</a>, but you mention <code>try</code>/<code>catch</code>. Now in MSVC C++ exceptions are implemented in terms of SEH, but are you solely interested in the C++ side of things or in general?</span>",
            "time": null
        },
        {
            "user": "Bob5421",
            "text": "<span class=\"comment-copy\">I mean a MSVC C++ try/catch. I am interested in the wide general thing</span>",
            "time": null
        },
        {
            "user": "peter ferrie",
            "text": "<span class=\"comment-copy\">I replaced my original answer because I was somehow describing the exception_record rather than the exception_registration_record.</span>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>EXCEPTION_REGISTRATION_RECORD is placed on the stack in anticipation of an exception occurring.  The \"try\" will put one there.  The record is part of a chain, for as many nested \"try\" statements as exist.  The nesting includes one function calling another function from within a try block.  Windows will also put a top-most handler there before the program starts, so there is always one on program start.</p>\n</div>",
            "votes": "4",
            "user": "peter ferrie",
            "time": "Feb 25, 2023 at 23:24",
            "is_accepted": true,
            "comments": []
        }
    ]
}