{
    "title": "Why does the Java compiler add an extra try-catch block?",
    "link": "https://reverseengineering.stackexchange.com/questions/3397/why-does-the-java-compiler-add-an-extra-try-catch-block",
    "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>Suppose we compile this method using Java 6+ compiler:</p>\n<pre><code>void test(int x) {\n    try {\n        x += 777;\n    } finally {\n        x -= 333;\n    }\n}\n</code></pre>\n<p>The disassembled code would look like this:</p>\n<pre><code>test(I)V\n    TRYCATCHBLOCK L0 L1 L2 null\n    TRYCATCHBLOCK L2 L3 L2 null\n   L0              // Start of try block\n    IINC 1 777     // The body of try block\n   L1              // Start of finally block in case of successful execution \n    IINC 1 -333    // Body of finally block\n    GOTO L4        // End of 'success' finally block \n   L2              // Start of finally block in case of exception\n    ASTORE 2       // Remember exception\n   L3\n    IINC 1 -333    // Duplicated body of finally block\n    ALOAD 2        // Load remembered exception\n    ATHROW         // Rethrow the exception \n   L4              // End of try/finally  \n    RETURN\n   L5\n</code></pre>\n<p>Obviously, this declaration specifies the \"try\" section and the beginning of the \"finally\" block:</p>\n<pre><code>    TRYCATCHBLOCK L0 L1 L2 null\n</code></pre>\n<p>But the next declaration looks strange:</p>\n<pre><code>    TRYCATCHBLOCK L2 L3 L2 null\n</code></pre>\n<p>Why does the Java compiler protect the exception while remembering it, and why does it specify itself as the handler recursively (i.e. the two <code>L2</code>s)?</p>\n</div>",
    "votes": "12",
    "answers": 2,
    "views": "1k",
    "tags": [
        "java",
        "byte-code"
    ],
    "user": "ponomandr",
    "time": "Jan 8, 2014 at 7:54",
    "comments": [
        {
            "user": "Devolus",
            "text": "<span class=\"comment-copy\">Does the same happen if you use <code>catch</code> instead of finally?</span>",
            "time": null
        },
        {
            "user": "ponomandr",
            "text": "<span class=\"comment-copy\">@Devolus No. It adds single     <code>TRYCATCHBLOCK L0 L1 L2 java/lang/Exception</code></span>",
            "time": null
        },
        {
            "user": "Daniel W. Steinbrook",
            "text": "<span class=\"comment-copy\">Same question on SO a few years ago: <a href=\"http://stackoverflow.com/questions/6386917/strange-exception-table-entry-produced-by-suns-javac\" title=\"strange exception table entry produced by suns javac\">stackoverflow.com/questions/6386917/â€¦</a></span>",
            "time": null
        },
        {
            "user": "avgvstvs",
            "text": "<span class=\"comment-copy\">I agree with Devolus.  I've never actually seen try{}finally{} in production code.</span>",
            "time": null
        },
        {
            "user": "avgvstvs",
            "text": "<span class=\"comment-copy\">Daniel, not the same question.  The question \"from a few years ago\" explicitly states that his case occurs even with the presence of a catch block.</span>",
            "time": null
        }
    ],
    "answers_data": [
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>A guess. As we can can see there is no actual duplication of code, the multiple trycatch blocks function as goto labels under different cases of what failed or not (since a finally clause is also present). If you follow the program flow you can see that no duplication  takes place.</p>\n</div>",
            "votes": "1",
            "user": "Nikos M.",
            "time": "May 25, 2014 at 2:34",
            "is_accepted": false,
            "comments": []
        },
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>I just disassembled this using java 8 compiler and the second trycatchblock is no longer being generated</p>\n<pre><code>test(I)V\n   TRYCATCHBLOCK L0 L1 L2 null\n  L0\n   IINC 1 777\n  L1\n   IINC 1 -333\n  L3\n   GOTO L4\n  L2\n   FRAME SAME1 java/lang/Throwable\n   ASTORE 2\n   IINC 1 -333\n   ALOAD 2\n   ATHROW\n  L4\n   FRAME SAME\n   RETURN\n  L5\n</code></pre>\n<p>My guess is this is some legacy handling that is ignored by the JVM</p>\n</div>",
            "votes": "1",
            "user": "bvella",
            "time": "Feb 1, 2018 at 19:09",
            "is_accepted": false,
            "comments": []
        }
    ]
}