{
    "title": "Getting funcap plugin work in IDA pro",
    "link": "https://reverseengineering.stackexchange.com/questions/5974/getting-funcap-plugin-work-in-ida-pro",
    "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>I am trying to use <a href=\"https://github.com/deresz/funcap\" rel=\"nofollow\">funcap plugin</a> in IDA pro 6.1. However, after loading the plugin (with <kbd>Alt</kbd>+<kbd>F7</kbd>) and pressing the debugger's run button, it returns me:</p>\n<pre><code>Internal error 30191 \n</code></pre>\n<p>Any idea what is the problem?</p>\n<p>P.S.: I have tried with both Python 2.6 and 2.7.</p>\n</div>",
    "votes": "3",
    "answers": 1,
    "views": "906",
    "tags": [
        "ida",
        "ida-plugin"
    ],
    "user": "user3403765",
    "time": "Jul 29, 2014 at 17:10",
    "comments": [],
    "answers_data": [
        {
            "content": "<div class=\"s-prose js-post-body\" itemprop=\"text\">\n<p>By any chance do you have the IDAStealth plugin installed? If so, do you have SEH debugging support features enabled? </p>\n<p>As per the bugfix for the plugin:</p>\n<pre><code>Bugfix: If any of the SEH debugging support features was used an \"internal error 30191\" would be raised in IDA as soon as the exception occurred in the debuggee\n</code></pre>\n<p><a href=\"http://newgre.net/idastealth\" rel=\"nofollow\">http://newgre.net/idastealth</a></p>\n</div>",
            "votes": "4",
            "user": "Fred Concklin",
            "time": "Jul 30, 2014 at 3:02",
            "is_accepted": false,
            "comments": [
                {
                    "user": "user3403765",
                    "text": "<span class=\"comment-copy\">Thanks for your reply. But, no. I don't.</span>",
                    "time": null
                }
            ]
        }
    ]
}